version: '3.8'

services:
  auth-postgres:
    image: postgres:15
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: authdb
    ports:
      - "55432:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

  authservice-api:
    build:
     context: ./services/AuthService
     dockerfile: AuthService.API/Dockerfile

    container_name: authservice-api
    depends_on:
      - auth-postgres
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=auth-postgres;Port=5432;Database=authdb;Username=admin;Password=admin123

  club-postgres:
    image: postgres:15
    container_name: club-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: clubdb
    ports:
      - "55433:5432"
    volumes:
      - club_pgdata:/var/lib/postgresql/data

  clubservice-api:
    build:
      context: ./services/ClubService
      dockerfile: ClubService.API/Dockerfile
    container_name: clubservice-api
    depends_on:
      - club-postgres
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=club-postgres;Port=5432;Database=clubdb;Username=admin;Password=admin123


  membership-postgres:
    image: postgres:15
    container_name: membership-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: membershipdb
    ports:
      - "55434:5432"
    volumes:
      - membership_pgdata:/var/lib/postgresql/data

  membershipservice-api:
    build:
      context: ./services/MembershipService 
      dockerfile: MembershipService.API/Dockerfile
    container_name: membershipservice-api
    depends_on:
      - membership-postgres
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=membership-postgres;Port=5432;Database=membershipdb;Username=admin;Password=admin123
volumes:
  auth_pgdata:
  club_pgdata:
  membership_pgdata:
